# Generated by Django 3.1.1 on 2020-10-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20201009_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
