# Generated by Django 3.1.1 on 2020-10-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_auto_20201010_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='website',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
