# Generated by Django 3.1.1 on 2020-10-08 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.CharField(max_length=255, null=True)),
                ('caption', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
