# Generated by Django 3.1.1 on 2020-10-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20201010_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='accessibility_caption',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
