# Generated by Django 3.1.1 on 2020-10-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_photo_accessibility_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
