# Generated by Django 3.1.2 on 2020-10-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
