# Generated by Django 3.1.2 on 2020-10-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_auto_20201011_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='thumbnail',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
